/*
DROP TABLE FIZICKAOSOBA;
DROP TABLE PRAVNAOSOBA;
DROP TABLE vlasnik;
DROP TABLE KVAR;
DROP TABLE DIOOBJEKT;
DROP TABLE OBJEKT;
DROP TABLE VROBJEKT;
DROP TABLE OSOBA;
DROP TABLE GRADSKACETVRT;
DROP TABLE GRAD;
*/

CREATE TABLE VROBJEKT
(
  sifVrObjekt INT NOT NULL,
  nazivVrObjekt VARCHAR(100) NOT NULL,
  PRIMARY KEY (sifVrObjekt),
  UNIQUE (nazivVrObjekt)
);

CREATE TABLE GRAD
(
  sifGrad INT NOT NULL,
  nazivGrad VARCHAR(100) NOT NULL,
  pbr INT NOT NULL,
  PRIMARY KEY (sifGrad),
  UNIQUE (pbr)
);

CREATE TABLE OSOBA
(
  OIB CHAR(11) NOT NULL,
  telBroj INT,
  eMail VARCHAR(50),
  PRIMARY KEY (OIB),
  UNIQUE (eMail),
  CONSTRAINT chkTelEmail CHECK (telBroj IS NOT NULL OR eMail IS NOT NULL)
);

CREATE TABLE FIZICKAOSOBA
(
  ime VARCHAR(50) NOT NULL,
  prezime VARCHAR(50) NOT NULL,
  OIB CHAR(11) NOT NULL,
  PRIMARY KEY (OIB),
  FOREIGN KEY (OIB) REFERENCES OSOBA(OIB)
);

CREATE TABLE PRAVNAOSOBA
(
  naziv VARCHAR(100) NOT NULL,
  OIB CHAR(11) NOT NULL,
  PRIMARY KEY (OIB),
  FOREIGN KEY (OIB) REFERENCES OSOBA(OIB)
);

CREATE TABLE GRADSKACETVRT
(
  sifGrCetvrt INT NOT NULL,
  nazivGrCetvrt VARCHAR(100) NOT NULL,
  sifGrad INT NOT NULL,
  PRIMARY KEY (sifGrCetvrt),
  FOREIGN KEY (sifGrad) REFERENCES GRAD(sifGrad),
  UNIQUE (nazivGrCetvrt)
);

CREATE TABLE OBJEKT
(
  sifObjekt INT NOT NULL,
  godinaGradnje INT NOT NULL,
  sifGrCetvrt INT NOT NULL,
  PRIMARY KEY (sifObjekt),
  FOREIGN KEY (sifGrCetvrt) REFERENCES GRADSKACETVRT(sifGrCetvrt),
  CONSTRAINT chkGodGr CHECK (godinaGradnje >= 1975)
);

CREATE TABLE DIOOBJEKT
(
  sifDioObjekt INT NOT NULL,
  povrsina NUMERIC(17,2) NOT NULL,
  brojProstorija INT NOT NULL,
  kat INT NOT NULL,
  sifObjekt INT NOT NULL,
  sifVrObjekt INT NOT NULL,
  PRIMARY KEY (sifDioObjekt),
  FOREIGN KEY (sifObjekt) REFERENCES OBJEKT(sifObjekt),
  FOREIGN KEY (sifVrObjekt) REFERENCES VROBJEKT(sifVrObjekt)
);

CREATE TABLE KVAR
(
  datumPrijava DATE NOT NULL,
  opis VARCHAR(200) NOT NULL,
  sifDioObjekt INT NOT NULL,
  OIB CHAR(11) NOT NULL,
  PRIMARY KEY (datumPrijava, sifDioObjekt),
  FOREIGN KEY (sifDioObjekt) REFERENCES DIOOBJEKT(sifDioObjekt),
  FOREIGN KEY (OIB) REFERENCES OSOBA(OIB)
);

CREATE TABLE vlasnik
(
  OIB CHAR(11) NOT NULL,
  sifDioObjekt INT NOT NULL,
  PRIMARY KEY (OIB, sifDioObjekt),
  FOREIGN KEY (OIB) REFERENCES OSOBA(OIB),
  FOREIGN KEY (sifDioObjekt) REFERENCES DIOOBJEKT(sifDioObjekt)
);