CREATE TABLE OSOBA
(
  JMBAG CHAR(10) NOT NULL,
  email VARCHAR(40) NOT NULL,
  ime VARCHAR(40) NOT NULL,
  prezime VARCHAR(40) NOT NULL,
  datRodjenja DATE NOT NULL,
  PRIMARY KEY (JMBAG),
  UNIQUE (email)
);

CREATE TABLE ZNAN_NAST_DJEL
(
  JMBAG CHAR(10) NOT NULL,
  PRIMARY KEY (JMBAG),
  FOREIGN KEY (JMBAG) REFERENCES OSOBA(JMBAG)
);


CREATE TABLE DOKTORAND
(
  godUpisStudij INT NOT NULL,
  JMBAG CHAR(10) NOT NULL,
  JMBAG_mentor CHAR(10) NOT NULL,
  PRIMARY KEY (JMBAG),
  FOREIGN KEY (JMBAG) REFERENCES OSOBA(JMBAG),
  FOREIGN KEY (JMBAG_mentor) REFERENCES ZNAN_NAST_DJEL(JMBAG)
);

CREATE TABLE PREDMET
(
  idPredmet INT NOT NULL,
  nazivPredmet VARCHAR(40) NOT NULL,
  ECTS INT NOT NULL,
  PRIMARY KEY (idPredmet),
  UNIQUE (nazivPredmet)
);

CREATE TABLE vrZvanja
(
  idVrZvanje INT NOT NULL,
  nazivZvanje VARCHAR(40) NOT NULL,
  PRIMARY KEY (idVrZvanje),
  UNIQUE (nazivZvanje)
);

CREATE TABLE upisuje
(
  JMBAG CHAR(10) NOT NULL,
  idPredmet INT NOT NULL,
  PRIMARY KEY (JMBAG, idPredmet),
  FOREIGN KEY (JMBAG) REFERENCES DOKTORAND(JMBAG),
  FOREIGN KEY (idPredmet) REFERENCES PREDMET(idPredmet)
);

CREATE TABLE IZBOR_U_ZVANJE
(
  datumIzbora INT NOT NULL,
  JMBAG CHAR(10) NOT NULL,
  idVrZvanje INT NOT NULL,
  PRIMARY KEY (datumIzbora, JMBAG),
  FOREIGN KEY (JMBAG) REFERENCES ZNAN_NAST_DJEL(JMBAG),
  FOREIGN KEY (idVrZvanje) REFERENCES vrZvanja(idVrZvanje)
);

CREATE TABLE VRSTA_AKTIVNOST
(
  idVrsta INT NOT NULL,
  nazivVrsta VARCHAR(40) NOT NULL,
  jePreduvjet_idVrsta INT,
  PRIMARY KEY (idVrsta),
  FOREIGN KEY (jePreduvjet_idVrsta) REFERENCES VRSTA_AKTIVNOST(idVrsta),
  UNIQUE (nazivVrsta)
);

CREATE TABLE AKTIVNOST
(
  datVrAktivnost TIMESTAMP NOT NULL,
  naslovSemAkt VARCHAR(40) NOT NULL,
  trajanje INT NOT NULL,
  JMBAG CHAR(10) NOT NULL,
  idVrsta INT NOT NULL,
  PRIMARY KEY (datVrAktivnost, JMBAG),
  FOREIGN KEY (JMBAG) REFERENCES DOKTORAND(JMBAG),
  FOREIGN KEY (idVrsta) REFERENCES VRSTA_AKTIVNOST(idVrsta)
);


CREATE TABLE sluša
(
  JMBAG_slusac CHAR(10) NOT NULL,
  datVrAktivnost TIMESTAMP NOT NULL,
  JMBAG_pristupnik CHAR(10) NOT NULL,
  PRIMARY KEY (JMBAG_slusac, datVrAktivnost, JMBAG_pristupnik),
  FOREIGN KEY (JMBAG_slusac) REFERENCES DOKTORAND(JMBAG),
  FOREIGN KEY (datVrAktivnost, JMBAG_pristupnik) REFERENCES AKTIVNOST(datVrAktivnost, JMBAG)
);

CREATE TABLE ocjenjujeAkt
(
  ocjena INT,
  JMBAG_komisija CHAR(10) NOT NULL,
  datVrAktivnost TIMESTAMP NOT NULL,
  JMBAG_pristupnik CHAR(10) NOT NULL,
  PRIMARY KEY (JMBAG_komisija, datVrAktivnost, JMBAG_pristupnik),
  FOREIGN KEY (JMBAG_komisija) REFERENCES ZNAN_NAST_DJEL(JMBAG),
  FOREIGN KEY (datVrAktivnost, JMBAG_pristupnik) REFERENCES AKTIVNOST(datVrAktivnost, JMBAG)
);